@startuml
namespace adapter {
    interface Analyzer  {
        + Analyze( []byte) error

    }
    class PowerfulAnalyzer << (S,Aquamarine) >> {
        + Visualize(dat []byte) error

    }
    class Record << (S,Aquamarine) >> {
        + Name string
        + Price float64
        + BuyNum int64
        + SellNum int64

    }
    class Stock << (S,Aquamarine) >> {
        + Data() ([]byte, error)

    }
    class jsonAnalyzerAdapter << (S,Aquamarine) >> {
        - analyzer *PowerfulAnalyzer

        + Analyze(dat []byte) error

    }
}

"adapter.Analyzer" <|-- "adapter.jsonAnalyzerAdapter"

"adapter.jsonAnalyzerAdapter" ..> "adapter.PowerfulAnalyzer"
"adapter.jsonAnalyzerAdapter" ..> "adapter.Record"

"adapter.Stock" ..> "adapter.Record"

@enduml
